/**
 * Zentrales Text-/Label-Modul.
 * Sämtliche deutschen UI-Texte (Deutsch Schweiz: kein «ß», Guillemets «…»)
 * gehören hierhin – keine deutschen Strings direkt in Komponenten.
 */
export const texts = {
  common: {
    platformName: 'Projektplattform',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    add: 'Hinzufügen',
    close: 'Schliessen',
    loading: 'Wird geladen …',
    saved: '✓ Gespeichert',
    unsaved: '● Ungespeicherte Änderungen',
  },
  landing: {
    loginTitle: 'Anmelden',
    loginEmail: 'E-Mail',
    loginPassword: 'Passwort',
    loginButton: 'Anmelden',
    loginPending: 'Anmeldung läuft …',
    forgotPassword: 'Passwort vergessen',
    toHub: 'Zum Dokumentenbereich',
    loggedInAs: 'Angemeldet als',
  },
  auth: {
    invalidCredentials: 'E-Mail oder Passwort ist falsch.',
    noProjectAccess: 'Dieses Konto hat keinen Zugang zu diesem Projekt.',
    linkInvalid:
      'Der Link ist ungültig oder abgelaufen. Bitte fordern Sie einen neuen an.',
    resetTitle: 'Passwort vergessen',
    resetIntro:
      'Geben Sie Ihre E-Mail-Adresse ein. Sie erhalten einen Link, um ein neues Passwort zu setzen.',
    resetButton: 'Link senden',
    resetPending: 'Wird gesendet …',
    resetSent:
      'Falls ein Konto mit dieser E-Mail existiert, wurde eine Nachricht mit den weiteren Schritten versendet.',
    newPasswordTitle: 'Neues Passwort setzen',
    newPasswordLabel: 'Neues Passwort',
    newPasswordRepeatLabel: 'Passwort wiederholen',
    newPasswordButton: 'Passwort speichern',
    newPasswordPending: 'Wird gespeichert …',
    passwordTooShort: 'Das Passwort muss mindestens 8 Zeichen lang sein.',
    passwordMismatch: 'Die Passwörter stimmen nicht überein.',
    backToLogin: 'Zurück zur Anmeldung',
    backToLanding: 'Zur Projektseite',
  },
  hub: {
    title: 'Dokumente',
    logout: 'Abmelden',
    loggedInAs: 'Angemeldet als',
    roleLabel: 'Rolle',
    emptyCategory: 'Noch keine Einträge.',
    addFallback: '+ Hinzufügen',
    addChild: '+ Unterposition',
    childrenLabel: 'Unterpositionen',
    download: 'Herunterladen',
    open: 'Öffnen',
    confirmDelete: 'Diesen Eintrag wirklich löschen?',
    savedToast: 'Änderungen gespeichert.',
    saveErrorToast: 'Speichern fehlgeschlagen. Bitte erneut versuchen.',
    deletedToast: 'Eintrag entfernt – noch nicht gespeichert.',
    addedToast: 'Eintrag erfasst – noch nicht gespeichert.',
    updatedToast: 'Eintrag geändert – noch nicht gespeichert.',
    leaveWarning: 'Es gibt ungespeicherte Änderungen.',
    dragHint: 'Zum Sortieren ziehen',
  },
  modal: {
    titleNew: 'Neuer Eintrag',
    titleEdit: 'Eintrag bearbeiten',
    fileSection: 'Datei oder Link',
    fileLabel: 'Datei hochladen',
    fileHint: 'PDF, Bilder, HTML, Excel usw.',
    chooseFile: 'Datei wählen',
    replaceFile: 'Datei ersetzen',
    currentFile: 'Aktuelle Datei',
    uploading: 'Wird hochgeladen …',
    uploadError: 'Upload fehlgeschlagen. Bitte erneut versuchen.',
    orExternalUrl: 'Oder externe URL',
    urlPlaceholder: 'https://…',
    requiredMissing: 'Bitte alle Pflichtfelder ausfüllen.',
    apply: 'Übernehmen',
    cancel: 'Abbrechen',
  },
  admin: {
    title: 'Adminbereich',
    projects: 'Projekte',
    loginTitle: 'Admin-Anmeldung',
    noAccess: 'Dieses Konto hat keinen Adminzugriff.',
    newProject: '+ Neues Projekt',
    statusLabel: 'Status',
    statusActive: 'Aktiv',
    statusArchived: 'Archiviert',
    nameLabel: 'Name',
    projectNoLabel: 'Projekt-Nr.',
    slugLabel: 'Slug',
    slugHint: 'Kleinbuchstaben, Ziffern, Bindestriche – z.B. «neubau-frauenfeld»',
    domainLabel: 'Domain (optional)',
    templateLabel: 'Aus Vorlage duplizieren',
    templateNone: '— keine Vorlage —',
    templateHint: 'Übernimmt Kategorien, Rollen, Matrix und Branding (keine Dokumente, keine Benutzer).',
    create: 'Projekt anlegen',
    creating: 'Wird angelegt …',
    createError: 'Anlegen fehlgeschlagen – Slug oder Domain bereits vergeben?',
    tabs: {
      daten: 'Daten',
      branding: 'Branding',
      kategorien: 'Kategorien',
      rollen: 'Rollen',
      benutzer: 'Benutzer',
    },
    exportLabel: 'JSON-Export',
    daten: {
      title: 'Projektdaten',
      subtitle: 'Untertitel',
      description: 'Beschrieb',
      infoCells: 'Info-Felder der Landingpage',
      addInfoCell: '+ Info-Feld',
      cellLabel: 'Bezeichnung',
      cellValue: 'Inhalt',
      removeCell: 'Entfernen',
      hero: 'Hero-Bild',
      heroUpload: 'Hero-Bild hochladen',
      uploading: 'Wird hochgeladen …',
    },
    branding: {
      title: 'Branding',
      management: 'Baumanagement',
      managementName: 'Firmenname',
      managementSuffix: 'Zusatz (optional)',
      logo: 'Logo',
      logoUpload: 'Logo hochladen',
      colors: 'Farben',
      colorLabels: {
        primary: 'Grau (Primär)',
        primaryDark: 'Dunkelgrau',
        accent: 'Akzent',
        accentDark: 'Akzent dunkel',
        bg: 'Hintergrund',
        line: 'Linien',
        ink: 'Text (Ink)',
      },
      fonts: 'Schriften',
      fontDisplay: 'Titelschrift',
      fontBody: 'Textschrift',
      preview: 'Live-Vorschau der Landingpage',
    },
    kategorien: {
      title: 'Kategorien',
      add: '+ Neue Kategorie',
      newLabel: 'Neue Kategorie',
      label: 'Bezeichnung',
      addLabel: '«Hinzufügen»-Text',
      keyLabel: 'Schlüssel',
      layout: 'Layout',
      layoutBig: 'Grosse Karten',
      layoutList: 'Listenkarten',
      allowChildren: 'Unterpositionen erlauben',
      fields: 'Feld-Schema',
      addField: '+ Feld',
      fieldLabel: 'Feldname',
      fieldPlaceholder: 'Platzhalter',
      fieldRequired: 'Pflicht',
      fieldBadge: 'Badge',
      moveUp: 'Nach oben',
      moveDown: 'Nach unten',
      confirmDeleteCategory:
        'Kategorie wirklich löschen? Alle zugehörigen Dokumente werden mitgelöscht.',
      confirmDeleteField: 'Feld aus dem Schema entfernen?',
    },
    rollen: {
      title: 'Rollen und Sichtbarkeit',
      add: '+ Neue Rolle',
      roleName: 'Rollenname',
      view: 'Sehen',
      upload: 'Hochladen',
      confirmDelete: 'Rolle wirklich löschen?',
      deleteError:
        'Rolle kann nicht gelöscht werden – es sind noch Benutzer zugewiesen.',
    },
    benutzer: {
      title: 'Benutzer',
      invite: 'Einladen',
      inviting: 'Wird eingeladen …',
      email: 'E-Mail',
      role: 'Rolle',
      projectAdmin: 'Projekt-Admin',
      deactivate: 'Deaktivieren',
      confirmDeactivate: 'Benutzer aus dem Projekt entfernen?',
      inviteSuccess: 'Einladung erstellt.',
      inviteLinkLabel: 'Einladungslink (falls kein E-Mail-Versand konfiguriert ist)',
      inviteError: 'Einladung fehlgeschlagen.',
      noMembers: 'Noch keine Benutzer in diesem Projekt.',
    },
  },
  tenantNotFound: {
    title: 'Projekt nicht gefunden',
    body: 'Unter dieser Adresse ist kein aktives Bauprojekt hinterlegt. Bitte prüfen Sie die Adresse oder wenden Sie sich an die Bauleitung.',
    devHint: 'Lokale Entwicklung: Tenant über «slug.localhost:3000» oder «?tenant=slug» aufrufen.',
  },
} as const;
