/**
 * Zentrales Text-/Label-Modul.
 * Sämtliche deutschen UI-Texte (Deutsch Schweiz: kein «ß», Guillemets «…»)
 * gehören hierhin – keine deutschen Strings direkt in Komponenten.
 */
export const texts = {
  common: {
    platformName: 'Projektplattform',
    save: 'Speichern',
    cancel: 'Abbrechen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    add: 'Hinzufügen',
    close: 'Schliessen',
    loading: 'Wird geladen …',
    saved: '✓ Gespeichert',
    unsaved: '● Ungespeicherte Änderungen',
  },
  landing: {
    loginTitle: 'Projekt-Login',
    projectNoPrefix: 'Projekt-Nr.',
    loginEmail: 'E-Mail',
    loginPassword: 'Passwort',
    loginButton: 'Anmelden',
    loginPending: 'Anmeldung läuft …',
    forgotPassword: 'Passwort vergessen',
    toHub: 'Zum Dokumentenbereich',
    loggedInAs: 'Angemeldet als',
  },
  auth: {
    invalidCredentials: 'E-Mail oder Passwort ist falsch.',
    noProjectAccess: 'Dieses Konto hat keinen Zugang zu diesem Projekt.',
    linkInvalid:
      'Der Link ist ungültig oder abgelaufen. Bitte fordern Sie einen neuen an.',
    resetTitle: 'Passwort vergessen',
    resetIntro:
      'Geben Sie Ihre E-Mail-Adresse ein. Sie erhalten einen Link, um ein neues Passwort zu setzen.',
    resetButton: 'Link senden',
    resetPending: 'Wird gesendet …',
    resetSent:
      'Falls ein Konto mit dieser E-Mail existiert, wurde eine Nachricht mit den weiteren Schritten versendet.',
    newPasswordTitle: 'Neues Passwort setzen',
    newPasswordLabel: 'Neues Passwort',
    newPasswordRepeatLabel: 'Passwort wiederholen',
    newPasswordButton: 'Passwort speichern',
    newPasswordPending: 'Wird gespeichert …',
    passwordTooShort: 'Das Passwort muss mindestens 8 Zeichen lang sein.',
    passwordMismatch: 'Die Passwörter stimmen nicht überein.',
    backToLogin: 'Zurück zur Anmeldung',
    backToLanding: 'Zur Projektseite',
  },
  modules: {
    sectionTitle: 'Module',
    badge: 'Modul',
    open: 'Modul öffnen',
    comingSoon: 'Dieses Modul wird mit dem nächsten Ausbauschritt freigeschaltet.',
    baukostenkontrolle: {
      label: 'Baukostenkontrolle',
      description: 'Kostenstand · Soll/Ist · Prognose',
    },
    leistungsverzeichnis: {
      label: 'Verkehr Leistungsverzeichnis',
      description: 'Vergabeübersicht · LV / Offerten / Werkverträge',
    },
  },
  bkk: {
    kpiOrig: 'KV orig.',
    kpiMut: 'KV mutiert',
    kpiVertrag: 'Verträge',
    kpiZahlung: 'Zahlungen',
    kpiOffen: 'Offen',
    deltaNeutral: '± 0 % gegenüber Baseline',
    deltaVsOrig: 'gegenüber Baseline',
    einsparung: 'Einsparung',
    baselinePrefix: 'Baseline',
    vertragPctSuffix: '% des KV mutiert vergeben',
    noVertraege: 'Keine Verträge erfasst',
    zahlungPctSuffix: '% der Vertragssumme bezahlt',
    noVertraegeYet: 'Noch keine Verträge',
    offenSubline: 'Vertrag ./. Zahlung',
    colPosition: 'Position (BKP)',
    colOrig: 'KV orig.',
    colMut: 'KV mutiert',
    colDelta: 'Δ %',
    colVertrag: 'Vertrag',
    colZahlung: 'Zahlung',
    colPctKv: '% v. KV',
    colPctVertrag: '% v. Vertrag',
    colStatus: 'Status',
    groupTotal: 'Zwischentotal',
    grandTotal: 'Gesamttotal',
    status: {
      offen: 'offen',
      vertrag: 'vertrag',
      bezahlt: 'bezahlt',
      teilbezahlt: 'teilbezahlt',
      ueber_kv: '> KV',
    },
    detailVertraege: 'Verträge',
    detailZahlungen: 'Zahlungen',
    addVertrag: '+ Vertrag',
    addZahlung: '+ Zahlung',
    addPosition: '+ Position',
    emptyEntries: 'Keine Einträge.',
    emptyModule:
      'Noch keine Positionen erfasst. Die Daten kommen mit der Migration des bestehenden Tools (P2-M4) oder über «+ Position».',
    confirmDeleteEntry: 'Diesen Eintrag wirklich löschen?',
    confirmDeletePosition:
      'Diese Position wirklich löschen (inkl. Verträge und Zahlungen)?',
    positionModalNew: 'Neue Position',
    positionModalEdit: 'Position bearbeiten',
    fieldBkp: 'BKP-Nr.',
    fieldName: 'Bezeichnung',
    fieldKvMut: 'KV mutiert (CHF)',
    kvMutHint:
      'Leer = Wert der aktiven Baseline. Neue Positionen sind nicht Teil bestehender Baselines – ihr Budget läuft über «KV mutiert».',
    fieldGroup: 'Gruppe',
    fieldHidden: 'Ausgeblendet',
    hiddenHint: 'Ausgeblendete Positionen zählen nur ins KV orig.',
    fieldNotiz: 'Notiz',
    notizPlaceholder: 'z.B. Nachtrag, Rückbehalt …',
    entryModalNewVertrag: 'Vertrag erfassen',
    entryModalNewZahlung: 'Zahlung erfassen',
    entryModalEditVertrag: 'Vertrag bearbeiten',
    entryModalEditZahlung: 'Zahlung bearbeiten',
    fieldBetrag: 'Betrag (CHF)',
    fieldDatum: 'Datum',
    fieldUnternehmer: 'Unternehmer',
    invalidAmount: 'Bitte einen gültigen Betrag eingeben.',
    duplicateBkp: 'Diese BKP-Nr. existiert bereits.',
    hiddenBadge: 'ausgeblendet',
    customBadge: 'zusätzlich',
    notInBaseline: 'nicht in dieser Baseline',
    baselines: {
      title: 'KV-Baselines',
      intro:
        'Die aktive Baseline ist die Referenz aller Vergleichszahlen. Bei grossen Projektänderungen wird ein revidierter KV zur neuen Referenz – die alte bleibt nachvollziehbar.',
      add: '+ Neue Baseline',
      activeBadge: 'Aktiv',
      setActive: 'Aktiv setzen',
      view: 'Ansehen',
      viewingBanner: 'Ansicht Baseline',
      viewingReadOnly: 'nur Lesen – Bearbeitung in der aktiven Baseline',
      backToActive: 'Zur aktiven Baseline',
      confirmActivate:
        'Diese Baseline aktiv setzen? Alle Vergleichszahlen (Δ %, Status, Totale) beziehen sich danach auf diese Baseline.',
      saveFirst: 'Zuerst speichern – Baseline-Aktionen arbeiten auf dem gespeicherten Stand.',
      modalTitle: 'Neue Baseline',
      fieldBezeichnung: 'Bezeichnung',
      bezeichnungPlaceholder: 'z.B. KV rev. 1',
      fieldDatum: 'Datum',
      sourceLabel: 'Werte übernehmen aus',
      sourceActive: 'Bisheriger (aktiver) Baseline',
      sourceActiveHint: 'Positionen ohne Wert bleiben ohne Wert.',
      sourceMut: 'KV mutiert (aktueller Stand inkl. Mutationen)',
      sourceMutHint: 'Der typische Fall: der revidierte KV wird neue Referenz; alle Positionen erhalten einen Wert.',
      createdToast: 'Baseline angelegt.',
      activatedToast: 'Baseline aktiviert – alle Vergleichszahlen beziehen sich jetzt darauf.',
      errorToast: 'Baseline-Aktion fehlgeschlagen. Bitte erneut versuchen.',
      empty: 'Noch keine Baseline vorhanden – ohne aktive Baseline zählt das KV-Total 0.',
    },
    groups: {
      title: 'BKP-Gruppen',
      add: '+ Neue Gruppe',
      modalNew: 'Neue Gruppe',
      modalEdit: 'Gruppe umbenennen',
      fieldDigit: 'Ziffer',
      fieldName: 'Bezeichnung',
      positionsCount: 'Positionen',
      deleteBlocked: 'Nur Gruppen ohne Positionen können gelöscht werden.',
      confirmDelete: 'Diese Gruppe wirklich löschen?',
      digitTaken: 'Für diese Ziffer existiert bereits eine Gruppe.',
      createdToast: 'Gruppe angelegt.',
      updatedToast: 'Gruppe umbenannt.',
      deletedToast: 'Gruppe gelöscht.',
      errorToast: 'Gruppen-Aktion fehlgeschlagen. Bitte erneut versuchen.',
    },
  },
  lv: {
    steps: {
      lv_erstellt: { label: 'LV erstellt', short: 'LV erstellt' },
      lv_versendet: { label: 'LV versendet', short: 'LV versendet' },
      off_erhalten: { label: 'Offerten erhalten', short: 'Offerten' },
      av_erstellt: { label: 'Angebotsvergleich erstellt', short: 'AV erstellt' },
      av_bh: { label: 'Angebotsvergleich an BH', short: 'AV an BH' },
      wv_erstellt: { label: 'Werkvertrag erstellt', short: 'WV erstellt' },
      wv_unt: { label: 'WV an Unternehmer', short: 'WV an Unt.' },
      wv_bh: { label: 'WV an Bauherrschaft', short: 'WV an BH' },
      wv_zurueck: { label: 'WV unterschrieben zurück', short: 'WV unterschr.' },
    },
    kpiTotal: 'Vergabeeinheiten',
    kpiLv: 'LV erstellt',
    kpiOff: 'Offerten erhalten',
    kpiWv: 'WV zurück',
    kpiOpen: 'Offen',
    colUnit: 'Vergabeeinheit',
    colStatus: 'Status',
    status: {
      offen: 'Offen',
      nach_aufwand: '⊘ Nach Aufwand',
      abgeschlossen: '✓ Abgeschlossen',
    },
    addUnit: '+ Vergabeeinheit',
    unitModalNew: 'Neue Vergabeeinheit',
    unitModalEdit: 'Vergabeeinheit bearbeiten',
    fieldBkp: 'BKP-Nr.',
    fieldName: 'Arbeitsgattung',
    fieldHidden: 'Ausgeblendet',
    fieldWerkvertrag: 'Werkvertrag (Dokument aus dem Hub)',
    werkvertragNone: '— kein Werkvertrag verknüpft —',
    werkvertragOpen: 'Werkvertrag öffnen',
    duplicateBkp: 'Diese BKP-Nr. existiert bereits.',
    confirmDeleteUnit:
      'Diese Vergabeeinheit wirklich löschen (inkl. Workflow-Stand)?',
    hiddenBadge: 'ausgeblendet',
    customBadge: 'zusätzlich',
    cellModalTitle: 'Workflow-Schritt',
    fieldDatum: 'Datum',
    fieldFreitext: 'Freitext',
    freitextPlaceholder: 'z.B. KW 34 oder Bemerkung',
    markDone: '✓ Erledigt',
    markNa: '⊘ Nach Aufwand',
    clearCell: 'Leeren',
    naHint:
      'Als «nach Aufwand» gilt eine Einheit, wenn alle vier WV-Schritte den ⊘-Marker tragen.',
    emptyModule:
      'Noch keine Vergabeeinheiten erfasst. Die Daten kommen mit der Migration des bestehenden Tools (P2-M4) oder über «+ Vergabeeinheit».',
    matrixTitle: 'Workflow-Matrix',
    unitCountSuffix: 'Vergabeeinheiten',
    scrollHint: '→ horizontal scrollen',
    legend: {
      title: 'Lesart',
      last: 'letzter erledigter Schritt',
      done: 'erledigt (tritt zurück)',
      doneMarker: 'erledigt ohne Datum',
      na: 'nach Aufwand',
      open: 'offen',
      dimmed: 'Abgeschlossene Zeilen sind gedimmt',
    },
  },
  hub: {
    title: 'Dokumente',
    logout: 'Abmelden',
    docCountSuffix: 'Dokumente',
    docCountSuffixOne: 'Dokument',
    moduleCountSuffix: 'Module',
    moduleCountSuffixOne: 'Modul',
    loggedInAs: 'Angemeldet als',
    roleLabel: 'Rolle',
    emptyCategory: 'Noch keine Einträge.',
    addFallback: '+ Hinzufügen',
    addChild: '+ Unterposition',
    childrenLabel: 'Unterpositionen',
    download: 'Herunterladen',
    open: 'Öffnen',
    confirmDelete: 'Diesen Eintrag wirklich löschen?',
    savedToast: 'Änderungen gespeichert.',
    saveErrorToast: 'Speichern fehlgeschlagen. Bitte erneut versuchen.',
    deletedToast: 'Eintrag entfernt – noch nicht gespeichert.',
    addedToast: 'Eintrag erfasst – noch nicht gespeichert.',
    updatedToast: 'Eintrag geändert – noch nicht gespeichert.',
    leaveWarning: 'Es gibt ungespeicherte Änderungen.',
    dragHint: 'Zum Sortieren ziehen',
    searchPlaceholder: 'Dokument oder BKP-Nr. suchen…',
    searchClear: 'Suche leeren',
    searchNoResults: 'Keine Dokumente zur Suche gefunden.',
    countOf: 'von',
  },
  modal: {
    titleNew: 'Neuer Eintrag',
    titleEdit: 'Eintrag bearbeiten',
    fileSection: 'Datei oder Link',
    fileLabel: 'Datei hochladen',
    fileHint: 'PDF, Bilder, HTML, Excel usw.',
    chooseFile: 'Datei wählen',
    replaceFile: 'Datei ersetzen',
    currentFile: 'Aktuelle Datei',
    uploading: 'Wird hochgeladen …',
    uploadError: 'Upload fehlgeschlagen. Bitte erneut versuchen.',
    orExternalUrl: 'Oder externe URL',
    urlPlaceholder: 'https://…',
    requiredMissing: 'Bitte alle Pflichtfelder ausfüllen.',
    apply: 'Übernehmen',
    cancel: 'Abbrechen',
  },
  admin: {
    title: 'Adminbereich',
    headerTitle: 'Administration',
    projects: 'Projekte',
    sections: {
      projects: 'Alle Bauprojekte der Plattform.',
      daten: 'Name, Nummer, Status und Inhalte der Landingpage.',
      branding:
        'Farben, Schriften und Bilder dieses Projekts. Statusfarben und BKK-Spaltentöne sind systemweit fix.',
      kategorien:
        'Das Feld-Schema definiert die Eingabemaske beim Erfassen von Dokumenten dieser Kategorie.',
      module:
        'Aktivierte Module erscheinen im Dokumenten-Hub – sichtbar nur für Rollen mit Freigabe (Bereich «Rollen»).',
      rollen:
        'Sichtbarkeit pro Dokumentkategorie · Modul-Zugriff getrennt in Sehen / Bearbeiten.',
      benutzer: 'Projektmitglieder einladen, Rollen zuweisen und deaktivieren.',
    },
    loginTitle: 'Admin-Anmeldung',
    noAccess: 'Dieses Konto hat keinen Adminzugriff.',
    newProject: '+ Neues Projekt',
    statusLabel: 'Status',
    statusActive: 'Aktiv',
    statusArchived: 'Archiviert',
    nameLabel: 'Name',
    projectNoLabel: 'Projekt-Nr.',
    slugLabel: 'Slug',
    slugHint: 'Kleinbuchstaben, Ziffern, Bindestriche – z.B. «neubau-frauenfeld»',
    domainLabel: 'Domain (optional)',
    templateLabel: 'Aus Vorlage duplizieren',
    templateNone: '— keine Vorlage —',
    templateHint: 'Übernimmt Kategorien, Rollen, Matrix und Branding (keine Dokumente, keine Benutzer).',
    create: 'Projekt anlegen',
    creating: 'Wird angelegt …',
    createError: 'Anlegen fehlgeschlagen – Slug oder Domain bereits vergeben?',
    tabs: {
      daten: 'Daten',
      branding: 'Branding',
      kategorien: 'Kategorien',
      rollen: 'Rollen',
      benutzer: 'Benutzer',
      module: 'Module',
    },
    exportLabel: 'JSON-Export',
    module: {
      title: 'Module',
      intro:
        'Aktivierte Module erscheinen im Dokumenten-Hub – sichtbar nur für Rollen mit Freigabe (Tab «Rollen»).',
      enabled: 'Aktiviert',
      hint: 'Nach dem Aktivieren die Freigaben in der Rollen-Matrix setzen – ohne Freigabe sehen nur Projekt-Admins das Modul.',
    },
    rollen_module: {
      view: 'Sehen',
      edit: 'Bearbeiten',
    },
    daten: {
      title: 'Projektdaten',
      subtitle: 'Untertitel',
      description: 'Beschrieb',
      infoCells: 'Info-Felder der Landingpage',
      addInfoCell: '+ Info-Feld',
      heroCaptionLeft: 'Hero-Bildunterschrift links',
      heroCaptionRight: 'Hero-Bildunterschrift rechts',
      loginSubtext: 'Login-Untertext',
      optionalHint: 'Leer = Element entfällt.',
      cellLabel: 'Bezeichnung',
      cellValue: 'Inhalt',
      removeCell: 'Entfernen',
      hero: 'Hero-Bild',
      heroUpload: 'Hero-Bild hochladen',
      uploading: 'Wird hochgeladen …',
    },
    branding: {
      title: 'Branding',
      management: 'Baumanagement',
      managementName: 'Firmenname',
      managementSuffix: 'Zusatz (optional)',
      logo: 'Logo',
      logoUpload: 'Logo hochladen',
      colors: 'Farben',
      colorLabels: {
        primary: 'Grau (Primär)',
        primaryDark: 'Dunkelgrau',
        accent: 'Akzent',
        accentDark: 'Akzent dunkel',
        bg: 'Hintergrund',
        line: 'Linien',
        ink: 'Text (Ink)',
      },
      fonts: 'Schriften',
      fontDisplay: 'Titelschrift',
      fontBody: 'Textschrift',
      preview: 'Live-Vorschau der Landingpage',
    },
    kategorien: {
      title: 'Kategorien',
      add: '+ Neue Kategorie',
      newLabel: 'Neue Kategorie',
      label: 'Bezeichnung',
      addLabel: '«Hinzufügen»-Text',
      keyLabel: 'Schlüssel',
      layout: 'Layout',
      layoutBig: 'Grosse Karten',
      layoutList: 'Listenkarten',
      allowChildren: 'Unterpositionen erlauben',
      fields: 'Feld-Schema',
      addField: '+ Feld',
      fieldLabel: 'Feldname',
      fieldPlaceholder: 'Platzhalter',
      fieldRequired: 'Pflicht',
      fieldBadge: 'Badge',
      moveUp: 'Nach oben',
      moveDown: 'Nach unten',
      sortMode: 'Sortierung',
      sortManual: 'Manuell (Drag)',
      sortByField: 'Automatisch nach Feld',
      sortField: 'Sortierfeld',
      sortDirection: 'Richtung',
      sortAsc: 'Aufsteigend',
      sortDesc: 'Absteigend',
      confirmDeleteCategory:
        'Kategorie wirklich löschen? Alle zugehörigen Dokumente werden mitgelöscht.',
      confirmDeleteField: 'Feld aus dem Schema entfernen?',
    },
    rollen: {
      title: 'Rollen und Sichtbarkeit',
      add: '+ Neue Rolle',
      roleName: 'Rollenname',
      view: 'Sehen',
      upload: 'Hochladen',
      confirmDelete: 'Rolle wirklich löschen?',
      deleteError:
        'Rolle kann nicht gelöscht werden – es sind noch Benutzer zugewiesen.',
    },
    benutzer: {
      title: 'Benutzer',
      invite: 'Einladen',
      inviting: 'Wird eingeladen …',
      email: 'E-Mail',
      role: 'Rolle',
      projectAdmin: 'Projekt-Admin',
      deactivate: 'Deaktivieren',
      confirmDeactivate: 'Benutzer aus dem Projekt entfernen?',
      inviteSuccess: 'Einladung erstellt.',
      inviteExisting:
        'Benutzer existierte bereits und wurde dem Projekt hinzugefügt – der Benutzer meldet sich mit seinem bestehenden Passwort an bzw. nutzt ‹Passwort vergessen›. Keine Einladungsmail nötig.',
      inviteLinkLabel: 'Einladungslink (falls kein E-Mail-Versand konfiguriert ist)',
      inviteError: 'Einladung fehlgeschlagen.',
      noMembers: 'Noch keine Benutzer in diesem Projekt.',
    },
  },
  ov: {
    report: {
      title: 'Positionenvergleich',
      bieterTitle: 'Eingebende Unternehmen',
      bieterSuffix: 'Offerten',
      infoBauvorhaben: 'Bauvorhaben',
      infoGattung: 'Arbeitsgattung',
      infoLv: 'LV-Nummer',
      infoManagement: 'Baumanagement',
      standPrefix: 'Stand',
      readingHint:
        'Hinweis zum Lesen: Die folgende Auswertung zeigt nicht alle Positionen, sondern jene mit den auffälligsten Preisunterschieden. Grün markiert ist jeweils der günstigste Preis pro Position, orange der teuerste. Beträge in CHF.',
      diffTitle: 'Grosse Unterschiede',
      diffSubtitle: 'Auffällige Positionen',
      colNpk: 'NPK',
      colBezeichnung: 'Bezeichnung',
      erkenntnisseTitle: 'Erkenntnisse der Vergleiche',
      erkenntnisseSuffix: 'Beobachtungen',
      pagePrefix: 'Seite',
    },
  },
  tenantNotFound: {
    title: 'Projekt nicht gefunden',
    body: 'Unter dieser Adresse ist kein aktives Bauprojekt hinterlegt. Bitte prüfen Sie die Adresse oder wenden Sie sich an die Bauleitung.',
    devHint: 'Lokale Entwicklung: Tenant über «slug.localhost:3000» oder «?tenant=slug» aufrufen.',
  },
} as const;
